# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode8.3
language: objective-c

jobs:
  include:
    - stage: test
      env: Client/Skin1
      script: xcodebuild clean build test -workspace Client/Client.xcworkspace -scheme Client1 -destination "platform=iOS simulator,name=iPhone 7 Plus,OS=10.3.1" ONLY_ACTIVE_ARCH=NO | xcpretty
    - env: Client/Skin2 
      script: xcodebuild clean build test -workspace Client/Client.xcworkspace -scheme Client2 -destination "platform=iOS simulator,name=iPhone 7 Plus,OS=10.3.1" ONLY_ACTIVE_ARCH=NO | xcpretty
    - env: Skins pod 
      script: xcodebuild clean build test -workspace Skins/Example/Skins.xcworkspace -scheme Skins-Example -destination "platform=iOS simulator,name=iPhone 6s Plus,OS=9.3" ONLY_ACTIVE_ARCH=NO | xcpretty
#    - env: Lint
#      script: swiftlint --config swiftlint.yml --strict
    - env: Pod Lint
      script:
        - cd Skins
        - pod lib lint --subspec=Skin1 --swift-version=3.1
        - pod lib lint --subspec=Skin2 --swift-version=3.1

