use_frameworks!

target 'Skins_Example' do
  pod 'Skins/Skin1', :path => '../'
  pod 'Skins/Skin2', :path => '../'
  
  # You can only install 1 skin per target, though that's only because I've named the files the same
  # pod 'Skins/Skin2', :path => '../'

  target 'Skins_Tests' do
    inherit! :search_paths

    
  end
end
